version: '3.8'
services:
  fastapi:
    build: .
    container_name: report_service
    image: report_service
    ports:
      - "19909:8000"
    volumes:
      - .:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]


